[[redirects]]
	from = "https://eboard.cds.fyi/zoom"
	to = "https://cornell.zoom.us/j/97974334609?pwd=b0g1QWRMTlRnNDNMeStnZjhieE9MUT09"
[[redirects]]
	from = "https://intsys.cds.fyi/*"
	to = "cds.fyi/intsys/:splat"
[[redirects]]
	from = "/intsys/drive"
	to = "https://drive.google.com/drive/u/2/folders/0B0oJ9v2w_sDRcUUyMHJzRU1xX1E?resourcekey=0-amc-yZnmDD58R80eS8gFZw"
